name: AAIF build and deploy

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: aaif
      repository: cynthia-sg/aaif-landscape
    secrets: inherit
