name: EBPF build and deploy

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  build-landscape:
    uses: cncf/landscape2-sites/.github/workflows/build-and-deploy.yml@main
    with:
      foundation: ebpf
      repository: ebpffoundation/landscape
    secrets: inherit
