name: O3DF validate settings

on:
  pull_request:
    branches:
      - main
    paths:
      - o3df/settings.yml

jobs:
  validate-landscape-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cncf/landscape2-validate-action@v2
        with:
          target_kind: settings
          target_path: o3df/settings.yml
